/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "tw-",
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#E4DCD5",
        grayLight: "#F4F5F6",
        graySoft: "#F7F7F8",
        grayMedium: "#DCDDE0",
        dividerLight: "#EFEFF1",
        dividerMedium: "#D6D7DC",
        aquaLight: "#B7DDFF",
        bgForm: "#FAFAFA",
        bgLayout: "#EBEBEB",
        bgTag: "#ECEDF0",
        bgActive: "#C1E6CF",
        bgCancelled: "#F0ACB0",
        bgCalendarBlue: "rgba(183, 221, 255, 0.30)",
        bgCalendarGreen: "rgba(193, 230, 207, 0.30)",
      },
      textColor: {
        primary: "#121316",
        secondary: "#525560",
        support: "#1890FF",
        required: "#D51E27",
        cancelled: "#732126",
        disabled: "#1C20243D",
        grayLight: "#505050",
        graySoft: "#838795",
        grayMedium: "#232429",
        aquaMedium: "#0A3C6B",
        tableHeader: "#3F4145",
        statusActive: "#0A4E22",
        statusInactive: "#1F2126",
      },
      borderColor: {
        primary: "#BABCC4",
        form: "#D6D7DC",
        info: "#B7DDFF",
        available: "#1890FF",
        subtle: "#EFEFF1",
        warning: "#F0ACB0",
        divider: "#ECEDF0",
        tableHeader: "#D6D8DB",
        calendarGreen: "#18BA51",
        cancelled: "#732126",
      },
      ringColor: {
        active: "#B7DDFF",
        divider: "#ECEDF0",
      },
      placeholderColor: {
        primary: "#838795",
      },
      fontSize: {
        xs: ["10px", "14px"],
        sm: ["12px", "20px"],
        lg: ["16px", "24px"],
        xl: ["18px", "28px"],
        xxl: ["20px", "30px"],
      },
    },
  },
  plugins: [],
};
